### ISSUE TITLE
BG 4th influence issue with empty deck and discard

### ISSUE THREAD

**Issue by dotdotdot-tts** [rogeriocamorim/duneBugSuggestionTracker#10]
when the deck and discard are empty and you go to a espionage with the player on 3rd BG influence, the pop-up comes up if you want to reset discard and draw a card, however both are empty; the reputation moves up to 4th influence, but the intrigue is not given to the player even though it says it was in the chat log.

i guess logic needs to recognize that both deck and discard are empty.

**Comment by dotdotdot-tts** [comment]
tested this and it does give intrigue now, but there is an issue. the intrigue is given for hitting the 4th BG influence before confirming the pop-up. intrigue should be given after resolving the pop-up, since you can cancel and not go there.

**Comment by Chatanga** [comment]
I haven't fixed anything regarding this issue... Maybe the problem with the intrigue was fixed as a side effect, but regarding the other part of the behavior, everything seems OK: canceling the popup doesn't cancel the action, just the automatic drawing of cards and the action still carries on behind your back. In fact, the popup is not linked to the action itself and no "hasDrawableCard" check is performed in general before any "sendAgent" action. Maybe it should, as well as a "hasNoRecallableAgent"...

**Comment by dotdotdot-tts** [comment]
ah i see, i assumed there was a "fix" in place because the behavior changed.

yeah that maybe it should, but it's a fringe case for sure.

**Comment by rogeriocamorim** [comment]
@dotdotdot-tts can this be closed?

**Comment by dotdotdot-tts** [comment]
i am not sure haha

**Comment by aaittouares** [comment]
@dotdotdot-tts i will close this one 
if you see it happen we'll reopen it

**Comment by dotdotdot-tts** [comment]
this should be reopened; so i tested this today and the spy popup should be resolved before getting the intrigue from going up to 4th position on BG track.

the way it works now is that, you can see the intrigue before you resolve the spy popup and in the rare instance you get an intrigue that gives you draw (i believe there are only 3 in the game), you gain information you should not have and can choose to not recall spy. this goes against the "resolving spy before gaining rewards" rule. 

the BG track is the only one where the 4th position reward reveals new information before spy is resolved. others are resource or spy reward.

**Comment by aaittouares** [comment]
this will not be reopened
From what i understand the issue you describe about spy and the issue about empty deck and discard are 2 different things.
Please open another issue for the spy issue.
Also if you could make the description a bit more clear for the new issue it would help.

**Comment by dotdotdot-tts** [comment]
fair, i had forgotten the initial issue brought up differed from what is being discussed recently. will do
