### ISSUE TITLE
makers hooks not locking

### ISSUE THREAD

**Issue by dotdotdot-tts** [rogeriocamorim/duneBugSuggestionTracker#11]
when you get maker hooks from sietch tabr, they are not locking after being placed so they can easily be selected and moved.

**Comment by Chatanga** [comment]
Wasn't intended, but why not locking it.

**Comment by dotdotdot-tts** [comment]
many times players have selected it and moved it around unintentionally so i think it would be helpful to lock after you get them.

**Comment by dotdotdot-tts** [comment]
live and working well, thank you!
