### ISSUE TITLE
SUGGESTION: regarding combat icons

### ISSUE THREAD

**Issue by dotdotdot-tts** [rogeriocamorim/duneBugSuggestionTracker#12]
it would be awesome if the combat icons can be coded so that when they are moved to the winning player's area, the banner for the combat would be placed on the board.

also, the combat icon for each combat should also be placed where you typically place VP markers to make it more clear to take after a combat is won.
![combat icon](https://github.com/rogeriocamorim/duneBugSuggestionTracker/assets/154347378/cc6212ca-96ef-4a65-9508-fd7e4f07a056)

**Comment by Chatanga** [comment]
Prepositioning an objective token is already planned. Same thing for converting them, but probably with a button in the dedicated area. Too much automated magic could be annoying sometimes.

**Comment by dotdotdot-tts** [comment]
i think the important part that needs to be automated is the banner aspect because people forget.

i thought the combat icon being the delivery vehicle for this functionality might be easiest, but you guys know best ^^

**Comment by Chatanga** [comment]
Sorry, by "banner" I was thinking of the VP token with banners on it, not the control token. You are correct about the objective/combat token replacing the old VP token as the vehicle for control tokens. This was a good idea in the old mod, it's still the case in Uprising.

**Comment by rogeriocamorim** [comment]
- Flag on the place is already done when token is taken
- Token more to top of combat for better visibility
- Just adding the token and getting vp is not yep. But you can use the objective token for now.

**Comment by Chatanga** [comment]
I'm not sure I understand here. Currently, collecting a combat objective token (i.e. a named token, not just any objective token) gives you control of the corresponding space. Additionally, when you stack two identical objective tokens, they are converted into VP. Is there a problem with any of these behaviors?
