### ISSUE TITLE
sietch tabr detonation does not remove shield wall

### ISSUE THREAD

**Issue by dotdotdot-tts** [rogeriocamorim/duneBugSuggestionTracker#13]
sietch tabr detonation option does not remove shield wall.

**Comment by Chatanga** [comment]
Wasn't intended actually, but moving it away with a the "atomics" sound would be nice.

**Comment by dotdotdot-tts** [comment]
haha yeah it would definitely be nice. there are cases where people forget to remove it and we have to think "didn't you blow up the wall?"

**Comment by dotdotdot-tts** [comment]
live and working well, thank you!
