### ISSUE TITLE
staban spy for makers does not give spice

### ISSUE THREAD

**Issue by dotdotdot-tts** [rogeriocamorim/duneBugSuggestionTracker#14]
when an opposing player goes to a makers space and staban has a spy for the space, staban should get a spice.

**Comment by Chatanga** [comment]
[Fixed small issues:](https://github.com/aaittouares/Dune_Uprising_TTS/commit/612e5d8a1c9a87a42d68a0504a4afae1bba5088a)

    Fixed Staban Tuek smuggling.
    Leader pool size for all selection methods.
    Spice Refinery shortcut when no spice.

**Comment by dotdotdot-tts** [comment]
nice! thank you

**Comment by dotdotdot-tts** [comment]
live and working well, thank you!
