### ISSUE TITLE
SUGGESTION: regarding spice refinery popup

### ISSUE THREAD

**Issue by dotdotdot-tts** [rogeriocamorim/duneBugSuggestionTracker#15]
gather support gives pop-up for choice of without water or with water only after player has 2 or more solari.

it would be great if spice refinery operates same way: give popup only after player has 1 or more spice.

**Comment by Chatanga** [comment]
[Fixed small issues:](https://github.com/aaittouares/Dune_Uprising_TTS/commit/612e5d8a1c9a87a42d68a0504a4afae1bba5088a)
- Fixed Staban Tuek smuggling.
- Leader pool size for all selection methods.
- Spice Refinery shortcut when no spice.

**Comment by dotdotdot-tts** [comment]
nice! thank you

**Comment by dotdotdot-tts** [comment]
live and working well, thank you!
