### ISSUE TITLE
sardukar issue

### ISSUE THREAD

**Issue by dotdotdot-tts** [rogeriocamorim/duneBugSuggestionTracker#17]
not sure what triggered the issue with sardukar (suddenly mid-game charged only 3 spice and gave no troops) but see below.

save:
[sardukar issue.json](https://github.com/rogeriocamorim/duneBugSuggestionTracker/files/13733603/sardukar.issue.json)

screenshot:
![sarduakar bug](https://github.com/rogeriocamorim/duneBugSuggestionTracker/assets/154347378/6372c044-c5a7-4dfa-b0ff-75765d7963bb)

**Comment by Chatanga** [comment]
Fix is on the way, both for the troops and the cost, but seriously: "Sardukar" ? Tss...

**Comment by aaittouares** [comment]
fixed

**Comment by dotdotdot-tts** [comment]
> Fix is on the way, both for the troops and the cost, but seriously: "Sardukar" ? Tss...

hahah oh no........ don't judge me (hides)
