### ISSUE TITLE
Sardaukar space costs 3 spice in four player game

### ISSUE THREAD

**Issue by 4thQueen** [rogeriocamorim/duneBugSuggestionTracker#18]
Sardaukar space pays three spice instead of four when clicking on it in a four player game. Potentially mixed code from Shaddam's personal board in six player, where Sardaukar does in fact cost three spice.

E: Apparently, getting swordmaster gives you permanent 2 swords, just like in six player. Might be a one-off bug that just loaded stuff from the six player ruleset.

**Comment by dotdotdot-tts** [comment]
this is a duplicate issue and apparently resolved already

**Comment by rogeriocamorim** [comment]
I think the first one is done o #17 
@4thQueen if there is 2 different issues can you create 2 different tickets?

**Comment by 4thQueen** [comment]
https://www.youtube.com/watch?v=vlRQ2IB5O20
Here's video evidence. It appears that in the second game, which I wasn't present for, Sardaukar was back to four spice but now two different players had 2 swords after getting Swordmaster. I can open a new ticket if that is what you deem appropriate, or rename this one.

**Comment by Chatanga** [comment]
This ghost swordmaster bonus is another problem, but that too has been solved and the fix is now available. No need to open a new ticket.
