### ISSUE TITLE
Faction bump problem

### ISSUE THREAD

**Issue by aaittouares** [rogeriocamorim/duneBugSuggestionTracker#2]
Tested on a 4 player hotseat
When I'm at Zero on a faction and click on position 2 of the faction (friendship), the token only goes up by 1 and in the log this indicates that I've gone up by 2.

**Comment by Chatanga** [comment]
Fixed in [Fixed bugs with high FPS configurations.](https://github.com/aaittouares/Dune_Uprising_TTS/commit/2009713e68e97415dd936118e303e8da7a53510f)

**Comment by aaittouares** [comment]
fixed and released in workshop
