### ISSUE TITLE
"Your turn" sound effect does not trigger for the first player of round 

### ISSUE THREAD

**Issue by supertopi** [rogeriocamorim/duneBugSuggestionTracker#22]
"Your turn" sound effect does not trigger for the first player of the round.
This seems to happen starting from round 2, so maybe has something to do with Makers + Recall button.

Sound effect does trigger correctly when the turn is passed to you by previous player End Turn button.

**Comment by Chatanga** [comment]
Yes, the transition from no active player (in combat) to one active player (round start) is silent, contrary to a transition from one player to another. Not sure if I can find a solution... But who needs a reminder that a new round has started and that they are the first player?

**Comment by supertopi** [comment]
Players are very used to the sound in the basegame/ix/immo mod.

It has been a couple times in my games, when the round starts that the first player does not act - and when reminded they told they didn't notice and were actually waiting for the sound.

It's not a big thing, quality of life improvement.

**Comment by aaittouares** [comment]
it's a limitation of TTS as far as i can see.
I don't think there's a solution for that unfortunately.
We'll have a quick look if there is, if not i'll close the issue.

**Comment by supertopi** [comment]
> it's a limitation of TTS as far as i can see. I don't think there's a solution for that unfortunately. We'll have a quick look if there is, if not i'll close the issue.

Curious to why this limitation does not affect the mod used in basegame/ix/immortality?

**Comment by Chatanga** [comment]
The two mods do not handle turn changes the same way. That being said, forcing the display of the turn marker each turn seems to be a solution. It also solves the problem of the “Add Your Turn Indicator” bug along the way.

**Comment by Chatanga** [comment]
[Fixed turn transition issues:](https://github.com/aaittouares/Dune_Uprising_TTS/commit/7a146f0bfe307cadbbccf978d1fcea86bba6f70b)
