### ISSUE TITLE
Turns break when loading a save (Uprising)

### ISSUE THREAD

**Issue by Tarpsukka** [rogeriocamorim/duneBugSuggestionTracker#23]
I don't know how to really reproduce this but it does happen more often than not when loading a saved game or autosave. The game just gives an error message saying "Error in Script (Global): chunk_3:(8844,42-44): attempt to index a nil value" and the turns are broken so that the game can't be continued anymore.

**Comment by Chatanga** [comment]
I am aware of this regression. Any saves made after the shield wall is destroyed will not be restored correctly. It has been corrected but not yet published. As a workaround, you can remove the shield wall from the global trash (top right corner) before saving.

**Comment by supertopi** [comment]
This also seems to affect rewinding time after shield wall has been destroyed. Which might technically be same as loading a save.

**Comment by rogeriocamorim** [comment]
Rewind it just a fancy reload option. ACT the same way

*Rogerio Dória Loyola-Camorim*

**Comment by Chatanga** [comment]
Fixed in [Fixed issues:](https://github.com/aaittouares/Dune_Uprising_TTS/commit/e68cdf5f44e2b1950e3d8d695fadf463d477e490)
