### ISSUE TITLE
Leader choices usually not randomized when reducing amount to choose from (Uprising)

### ISSUE THREAD

**Issue by Tarpsukka** [rogeriocamorim/duneBugSuggestionTracker#24]
Since my offline group picks leaders from 5 random choices, I wanted to try this in TTS as well. It seems like it works sometimes but most of the time it just gives Gurney, Amber, Staban, Feyd and Jessica to choose from. Even when it changed some of the other leaders, for me at least, Amber and Staban seem to always be in the pool to choose from.

**Comment by Chatanga** [comment]
If by “sometimes” you mean “never,” you’re right. Shuffling is only done in hidden mode for historical reasons, but this should no longer be the case now (so yeah, definitely something to fix).

**Comment by Chatanga** [comment]
Fixed in [Fixed not randomized leaders when not hidden.](https://github.com/aaittouares/Dune_Uprising_TTS/commit/6e34e292a96d7bb20e333c95d15acebedb1ba902)
