### ISSUE TITLE
spy issue with sietch and shipping+accept contracts spy issue

### ISSUE THREAD

**Issue by dotdotdot-tts** [rogeriocamorim/duneBugSuggestionTracker#25]
first off, amazing work and thank you for the popup spy feature, it's made gameplay feel so much smoother! very well implemented for sietch + spice refinery double spy detection and resolution as well.

bugs:
- when you have sietch spy and go to sietch, the pop-up comes up twice. 
- spy functionality at shipping + accept contracts does not seem to work. pop-ups do not occur because spies are not detected. right click functionality also does not work.

**Comment by aaittouares** [comment]
it seems sietch spy popup is a thing
we had something like what you describe during a game before.

we will test the shipping and accept contracts bug

Also can you make another issue for your suggestions please ?
I would like to keep bug issues and suggestions issue separate so i can close bugs when solved
So please make bug issues and suggestions issues separate for your next report. Also try to keep focused on one subject inside the issue you report.

**Comment by dotdotdot-tts** [comment]
ok will do, i removed suggestions from this issue and will create a new one

**Comment by Chatanga** [comment]
[Fixed issues:](https://github.com/aaittouares/Dune_Uprising_TTS/commit/1b1274369259c2b3897f2efd634cd7f9b6631be8)
- Misnomed CHOAM outpost snappoint.
- Duplicated dialog for sietch Tabr.
