### ISSUE TITLE
Issue with intrigue card "Unexpected Allies" without Makers Hook

### ISSUE THREAD

**Issue by 4thQueen** [rogeriocamorim/duneBugSuggestionTracker#3]
Unexpected Allies is the only way to acquire worms without Makers Hooks in the game. The mod does not allow players to add worms unless they already have Makers Hooks. The workaround we got to was just adding three strength manually and pretending there was a worm, but it would be nice to have a real solution to this.

**Comment by Chatanga** [comment]
Fixed in [Fixed sandworm button availability.](https://github.com/aaittouares/Dune_Uprising_TTS/commit/faa92673cab02ecfad5574f0d99d6b93ec3f7db8)

**Comment by aaittouares** [comment]
fixed and released in workshop
