### ISSUE TITLE
BG track 4th position reward and spy popup interaction

### ISSUE THREAD

**Issue by dotdotdot-tts** [rogeriocamorim/duneBugSuggestionTracker#30]
scenario - player has a spy on BG and player is on 3rd position on the BG track

when player is first to go to a BG spot, the spy popup will ask player to draw a card, but player already has the intrigue in hand from moving up to 4th position on BG track and knows what it is before resolving the spy popup.

this goes against the "resolving spy before gaining rewards" rule.

in the rare instance you get an intrigue that gives you card draw (i believe there are only 3 in the game), you gain information you should not have and can choose to not recall spy. the BG track is the only faction where the 4th position reward reveals new information before spy is resolved. others are resource or spy reward.

the logic progression should be that if there is a spy and player is first to the spot, the spy popup should be resolved first before the influence marker moves up.

**Comment by Chatanga** [comment]
That's clearly not how it is coded and I can't reproduce this bug. The action, including changing factions, is only performed after the user chooses an option. Could you test it again? Just to be sure we are testing the same version.

**Comment by dotdotdot-tts** [comment]
you're right, i tested it today and it's behaving as you described. 

i wrote the note down right after the january 5 update with the spy popups, which is where i saw the behavior.

didn't have time to post the issues from my notes until yesterday, which is why you saw a flurry of them; didn't expect a fix in place already, nice!
