### ISSUE TITLE
BUG: Game board shrinks during Setup

### ISSUE THREAD

**Issue by supertopi** [rogeriocamorim/duneBugSuggestionTracker#31]
After latest update to mod some people including myself have encountered this bug.

1. Join game (not host), board looks normal.
2. Host presses Setup
3. Game board graphic shrinks to a very small size making it unable to interact with.
4. Leaving and rejoining the game fixes this issue

**Comment by Chatanga** [comment]
This is an old problem, perhaps more common when selecting the French language. This is not a bug per se, but simply the way TTS works which is inherently unreliable. The more updates/dynamic creations/asset loads you perform in a short period of time, the more likely you are to get this type of silent corruption on guests (and only on guests). There is no perfect solution to this problem, just workarounds to sufficiently dilute their occurrences. I'm thinking about different approachs, but in the meantime you already know how to fix it: quit and rejoin (or save and reload).

**Comment by dotdotdot-tts** [comment]
right click > state > change to 2 then back to 1, is a faster workaround

also haven't seen this one yesterday. maybe fixed?

**Comment by supertopi** [comment]
> right click > state > change to 2 then back to 1, is a faster workaround
> 
> also haven't seen this one yesterday. maybe fixed?

right click what? is still occurring

**Comment by rogeriocamorim** [comment]
@supertopi Is that still a thing?
If yes let me know and i can re-open
