### ISSUE TITLE
Turn not ending when playing Fold Space

### ISSUE THREAD

**Issue by BlaXeBane** [rogeriocamorim/duneBugSuggestionTracker#32]
My 4-player game encountered a bug where clicking the  "End Player's Turn" in the top middle of the screen just repeats that players turn. This happens when they play Fold Space in the agent zone.

1. Set up game for 4 players.
2. Have a player play the Fold Space card as a agent card as the first card on the first turn.
3. Put an agent somewhere
4. Click end turn 
My players were not able to click end turn. It just repeated their turn over and over again.

We tried dragging the Fold Space card into the Trash zone on the player's board, and tried dragging it back into the agent zone (to see if it auto puts it in), no luck

**Comment by BlaXeBane** [comment]
The end turn square button goes through this issue, will just use the button instead

**Comment by Chatanga** [comment]
1. This is how things work in this mod. The native "turn button" will **always** cycle the current player and the "end turn" button should be used instead.
2. Fold space? No such card exists in Uprising. Space-time folding perhaps? Regardless, the “End Turn” button doesn’t care what card you played during your turn.
