### ISSUE TITLE
No Makers + Recall button appearing

### ISSUE THREAD

**Issue by Tarpsukka** [rogeriocamorim/duneBugSuggestionTracker#34]
After "Phase: Combat" there was an error "Error in Script (Global): chunk_3:(19805,10-22): assertion failed!" As for reproducing this... the only thing I could think of is that someone moved the conflict card before the last player clicked "End turn".

**Comment by Chatanga** [comment]
The error is actually linked to the absence of an active conflict card. Does this deserve a correction? Probably not. It happens once a year and it is easy to rollback the game to fix it. That being said, this is still a useful information.
