### ISSUE TITLE
Suggestion: Delay and stagger intrigue acquisition at Secrets

### ISSUE THREAD

**Issue by 4thQueen** [rogeriocamorim/duneBugSuggestionTracker#36]
Noticed that Intrigue acquisition at Secrets is instantaneous. Which is great! Unless there are players with four or more intrigues... in which case it's impossible to know which intrigue came from which player or the deck. This can be very important if you steal a combat or VP intrigue, since knowing that an opponent knows about it will greatly alter how you and them both play. And this gets even more complicated when there's more than one player who gets stolen from! Now you don't even know WHO knows what.

Staggering the acquisition of intrigues with a delay could help mitigate this issue, at the risk of slowing the pace of the game. Not sure if this is a feasible solution, however.

**Comment by rogeriocamorim** [comment]
> it's impossible to know which intrigue came from which player or the deck. 


You can check the logs
![image](https://github.com/rogeriocamorim/duneBugSuggestionTracker/assets/1370987/d8b0ac3d-3555-4a49-82ab-df41d6c56510)
![image](https://github.com/rogeriocamorim/duneBugSuggestionTracker/assets/1370987/85b73ee7-4ab6-43b4-b3c6-2354cc4fa4ce)

**Comment by 4thQueen** [comment]
Alright well then. Guess I should unhide chat I guess.
