### ISSUE TITLE
Suggestion: Mouse, Ornithopter, Crysknife counting as VP Tokens

### ISSUE THREAD

**Issue by elessar-gh** [rogeriocamorim/duneBugSuggestionTracker#37]
First of all, thanks for an amazing mod and for all your hard work on it! Just wanted to offer this minor suggestion since I've heard multiple people share the sentiment:

- Currently the VP tokens for Combat Match is very far away from the play area and not the easiest to grab, since it's packed tightly in with a bunch of other VP tokens. When someone gets a combat match, they go digging for the token and set it on their VP track, and then add the relevant symbol (Desert Mouse, Crysknife, Ornithopter) on top of it anyway to indicate what the match was.

- I think it would be pretty natural and convenient for the three combat symbol tokens (Mouse, Crysknife, Ornithopter) to simply serve as a VP token itself. They are used frequently each game, and are already located conveniently close to the board area. When you get a combat match, you would simply move the previously unmatched token from your play area onto your VP track, and it would get automatically recorded on the public score track. 

- If you don't like that idea, I'd advocate for bringing the Combat Match VP token down to the bottom of the board, next to the three Combat symbol tokens, making it easier to grab.

**Comment by Chatanga** [comment]
In a version that has not yet been released, stacking two similar objective tokens converts them into a single VP objective token. If VP tokens are ever reworked, however, things could change.

**Comment by elessar-gh** [comment]
Awesome! It's a minor thing, but I think it would be nice if the converted VP token still shows which symbol match it was.

**Comment by rogeriocamorim** [comment]
Released.
