### ISSUE TITLE
Issue with dialogue box when using two spies

### ISSUE THREAD

**Issue by elessar-gh** [rogeriocamorim/duneBugSuggestionTracker#38]
It's a rare occurrence for this to matter, but I could see it causing drama in a competitive setting and wanted to at least make mention of it.

If you have two spies connect to one space (e.g. on either side of Research Station), the rules allow you to use one spy to infiltrate, and use the other spy to gather intelligence (draw a card). 

Currently, I believe the mod just asks: "Select from wich observation post you recall your spy" [to infiltrate]

I think it should first ask:
"Would you like to recall a spy to draw a card?"

**- If Yes:** No more questions. Both spies are pulled.

**- If No:** "Which spy would you like to recall to infiltrate?"

As it is now, the player would need to verbally tell the table that they are pulling a spy for the card draw BEFORE drawing from research station. And it would be easy to forget that, since the mod usually serves as the gatekeeper for that decision.

**Comment by Chatanga** [comment]
Fixed in: [Fixed infiltrate + gather intelligence combo.](https://github.com/aaittouares/Dune_Uprising_TTS/commit/47f6ca1af83daa62524fe1366f857e3868157a45)

Note that forcing a recall (right click) only applies to the infiltration part in this specific case.

**Comment by rogeriocamorim** [comment]
Released
