### ISSUE TITLE
Add Foldspace Card to Ilesa Ecaz as by rule books.

### ISSUE THREAD

**Issue by rogeriocamorim** [rogeriocamorim/duneBugSuggestionTracker#39]
Since we now have Rise of ix leaders we need to have the Foldspace for her to buy.
![image](https://github.com/rogeriocamorim/duneBugSuggestionTracker/assets/1370987/cef03daf-d28a-4f95-b188-bac3152c8cc6)

**Comment by aaittouares** [comment]
they are spawned on the ilesa leader card when you select her
Closing this ticket
