### ISSUE TITLE
Worm model not loading

### ISSUE THREAD

**Issue by cartmanbeck** [rogeriocamorim/duneBugSuggestionTracker#4]
I'm trying to load the current version of the Dune Imperium Uprising++ mod using 4-player hotseat mode. The custom model for the worm (http://cloud-3.steamusercontent.com/ugc/998052610365832795/2A6B1BDA4833D2B41CC518418B702E4D0D36ED2D/) will not load in (the Custom Model modal repeatedly comes up and throws an error when I hit Import), meaning I can't use worms in the mod at all. 
![image](https://github.com/rogeriocamorim/duneBugSuggestionTracker/assets/8007678/8a4aa888-9379-4068-a627-2b08d69a6354)

**Comment by Chatanga** [comment]
Can you download the URL from a browser? And then try to use it as a local file to fix the model in TTS?

**Comment by Chatanga** [comment]
Not reproductible and nobody interested in, so let's close this non issue.

**Comment by cartmanbeck** [comment]
Sorry I didn't get a message about the requested response until this was closed. I did download the file and was able to use it as a local file, so I assume it's some sort of issue with my computer and the specific URL where the file is stored.
