### ISSUE TITLE
Wrong intrigue counts

### ISSUE THREAD

**Issue by scmccarthy** [rogeriocamorim/duneBugSuggestionTracker#45]
![image](https://github.com/rogeriocamorim/duneBugSuggestionTracker/assets/4999445/fd03a51e-0950-4a94-a8d2-01e1c4e66795)
There should be 2 dispatch an envoy and 1 councilor's dispensation, not the other way around.

I verified in game after I spotted it in the code.

Reference: https://boardgamegeek.com/thread/2624520/intrigue-card-deck-list

**Comment by aaittouares** [comment]
totally right about the count
i'll fix that asap
thanks for the report

**Comment by aaittouares** [comment]
fixed in https://github.com/aaittouares/Dune_Uprising_TTS/commit/466a2e68f34521f662dfa4919191e3dc1a2fdcb8
and deployed to public version
