### ISSUE TITLE
Bigger main board?

### ISSUE THREAD

**Issue by BShadow993** [rogeriocamorim/duneBugSuggestionTracker#46]
After several streams, have been getting feedback that the centre board is too small compared to the player areas. Course those have more stuff in so will be bigger than Ix/Immo but maybe an adjustment can be made to make viewing easier? Especially on small devices like phones and laptops.

**Comment by Chatanga** [comment]
I guess the layout could be optimized, the content on each play board packed more tightly, but it's too much work in a TTS mod for too little a benefit I'm afraid. Direwolf (or others) would have released an Uprising version of its mobile app before it happens.

**Comment by BShadow993** [comment]
I imagine it's not anywhere as easy to do as it might seem otherwise. No worries.
