### ISSUE TITLE
Removal of shuffling non-players into game seats

### ISSUE THREAD

**Issue by BShadow993** [rogeriocamorim/duneBugSuggestionTracker#48]
I know this is brought over from the previous mod but would like this to be (at least optionally) disabled. It means that if ever more than one person is spectating a game (like if I'm covering a match) then players not playing get shuffled onto a seat and it's impossible to sort it out and the table is forced to reload the game and do it again. (The GPI finals took 5-6 restarts because of this) The TTS host can already set people to colours if they aren't already seated so the draft can happen. I don't feel this feature is needed and actively causes delays in any game where someone is spectating.

**Comment by Chatanga** [comment]
I doubt this was a feature in the previous mod (whichever mod you're thinking of). Personally, I'm not used to having spectators, at least at the start of a match, I never realized it was a problem. Obviously this is annoying in your setup, but luckily the solution is quite simple.

**Comment by BShadow993** [comment]
It was a thing in the Ix Immo mod. Thanks.

**Comment by Chatanga** [comment]
[Fixed randomization of payer positions to ignore spectators.](https://github.com/aaittouares/Dune_Uprising_TTS/commit/5521b18252f1eb2417c7389501b86c7fa135ed13)

**Comment by BShadow993** [comment]
Many thanks
