### ISSUE TITLE
TTS Freezing/skipping exactly every 10 minutes, only when using this mod

### ISSUE THREAD

**Issue by cartmanbeck** [rogeriocamorim/duneBugSuggestionTracker#49]
This is a weird one. For the last week or so, when I am playing using this mod and only this mod, every ten minutes EXACTLY I will experience TTS freezing up for about 20-30 seconds, sometimes resulting in a crash but more often just resulting in being kicked from whatever online game I'm playing. It's truly clockwork, exactly every 10 minutes from when I start the mod. 

Have you recently added a timer to some part of the script that could be causing this? This doesn't happen in other TTS mods or any other games or programs I'm using. 

System: 
AMD Ryzen 5 4600G
16G RAM
Win 11 Pro
GTX 1080Ti video card
Game is installed on a solid state drive (and I've tried moving the game files to a different SSD, didn't make a difference)

**Comment by Chatanga** [comment]
Indeed, it's weird. Such a timer obviously does not exist. Is your memory usage (Task Manager) steadily increasing in this situation? Note that scripts are only run on the host and any freeze should be experienced by all players.

**Comment by cartmanbeck** [comment]
Thanks for the reply. I'll try testing this today to see if the memory usage is increasing. If so, do you have any suggestions on what I could do next if that's the issue?

**Comment by cartmanbeck** [comment]
Okay so I watched the system hardware utilization while playing, and the freeze-up happened, and one of my hard drives spiked to 100%. Weirdly, it's not the HD that the game is installed on, but I'll try unplugging that drive and see if that fixes the issue. 
Thanks for your suggestion!
