### ISSUE TITLE
Button to flip Lady Jessica disappears after a rewind/reload

### ISSUE THREAD

**Issue by 4thQueen** [rogeriocamorim/duneBugSuggestionTracker#5]
The button labeled "Use Other Memories" on Lady Jessica's card disappears after a rewind or reload of the game, rendering it impossible to flip her normally. A simple workaround of un-toggling Lock on the card allows for manually flipping.

**Comment by Chatanga** [comment]
Fixed in [Static deck assembly.](https://github.com/aaittouares/Dune_Uprising_TTS/commit/a9521c2d2efb7da0e76e432b5d6f6f9d05efb9a5)

**Comment by dotdotdot-tts** [comment]
live + tested this and it's working well, thank you!
