### ISSUE TITLE
Combat Tie Helpcard

### ISSUE THREAD

**Issue by BShadow993** [rogeriocamorim/duneBugSuggestionTracker#50]
In Ix Immo mod, there's a reference card at bottom of table describing how tiebreak rewards are resolved. The rules are the same in Uprising so can the card be added?

**Comment by rogeriocamorim** [comment]
Added on the mod.
W8 Release.
![image](https://github.com/rogeriocamorim/duneBugSuggestionTracker/assets/1370987/0fa9690b-590f-44d3-b8c7-dd967dcdc718)
