### ISSUE TITLE
Error in Script after loading a save

### ISSUE THREAD

**Issue by Supaflyevilguy** [rogeriocamorim/duneBugSuggestionTracker#51]
We usually don't finish a game in a night so we've been trying to save and come back the next day. Getting the following error in chat:
"Error in Script (Global): chunk_3:(17050.47-59):attempt to index a null value"

Agent Turn and Reveal Turn buttons are then missing and we cannot proceed with the game.

Thanks.

**Comment by Chatanga** [comment]
Thanks for including the log error line. Unfortunately I can't match it with any of the latest versions in the repository. Can you post your entire broken save file here instead?

**Comment by Supaflyevilguy** [comment]
[TS_Save_63.json](https://github.com/rogeriocamorim/duneBugSuggestionTracker/files/15030250/TS_Save_63.json)

Thanks for looking at this!

**Comment by Chatanga** [comment]
[TS_Save_64.json](https://github.com/rogeriocamorim/duneBugSuggestionTracker/files/15043334/TS_Save_64.json)

It appears that games without the CHOAM cannot be reloaded. The mod will be fixed, but in the meantime I've already fixed your save.

**Comment by Supaflyevilguy** [comment]
Thanks so much! Appreciate it!

**Comment by Chatanga** [comment]
[Fixed the loading of a game without the CHOAM module.](https://github.com/aaittouares/Dune_Uprising_TTS/commit/505d624830c820a874798ef698d80e0f103ba0d0)

**Comment by aaittouares** [comment]
released
