### ISSUE TITLE
Muad'Dib automatic worm intrigue draw

### ISSUE THREAD

**Issue by friachitts** [rogeriocamorim/duneBugSuggestionTracker#52]
Would be nice if the intrigue from Muad'Dib passive was automatically drawn to the player's hand.
I am sure this is forgotten a fair amount of times and always causes weird situation when the player realizes they forgot.
It is also a mandatory draw.

**Comment by Chatanga** [comment]
[Automated the 'Unpredictable foe' ability.](https://github.com/aaittouares/Dune_Uprising_TTS/commit/c1de08160694f4ab41ac5f3d423e270ddf2fdde6)

**Comment by rogeriocamorim** [comment]
Muad'Dib become a bit more unpredictable. Lol

**Comment by aaittouares** [comment]
released
