### ISSUE TITLE
Flag sometimes does not show up for the owner

### ISSUE THREAD

**Issue by westonsandland** [rogeriocamorim/duneBugSuggestionTracker#53]
Occasionally, when a player wins a shield wall combat, their flag will not show up visually for themselves despite the fact that they move the icon token into their play area (which normally causes the flag to appear). Typically, the rewards of the flag are provided despite this visual glitch, but there have been reports of that failing as well.

Typically the flag will show up for other players but not for the one that actually owns the flag.

**Comment by Chatanga** [comment]
[Potential fix for missing control flag.](https://github.com/aaittouares/Dune_Uprising_TTS/commit/cfaba372d3914abedd6df3644c40ac83c4893aa1)

I've found a potential problem, but I've not been able to reproduce the bug. If it happen again, additionnal information would be useful (in particular, does the involved player also convert two objectives into a VP?).

**Comment by aaittouares** [comment]
released
