### ISSUE TITLE
Add Your Turn Indicator (Uprising)

### ISSUE THREAD

**Issue by koekto32165** [rogeriocamorim/duneBugSuggestionTracker#6]
Add an indicator that it's your turn to the Uprising mod. Ever since the "pass turn" button that is visible in the DI mod was removed, people tend to miss the start of their turn.

**Comment by Chatanga** [comment]
The colored frame around the active player is hard to miss though... But if your fellow players are doozing over their keyboard you are still able to to activate the native turn to bring back the wake up sound. You still need to use the board button to end your turn though.

**Comment by rogeriocamorim** [comment]
So the native button can still be used. So it will not have any effect over
the board right ?

**Comment by Chatanga** [comment]
Using it won't do anything, it will simply cycle the current player... except in combat where there is no such player. It could become desynchronized in this case, but it properly resets when needed. That being said, the colored frame is intended to be an obvious clue for all players. Is there any problem regarding it (it was with the older versions) ?

**Comment by dotdotdot-tts** [comment]
it would be very helpful if the framed border can be thicker to be more obvious. players have expressed that even when looking at the board, it's hard to notice that it's your turn sometimes.
