### ISSUE TITLE
Add Explanation when Send Agent Fails (Uprising)

### ISSUE THREAD

**Issue by koekto32165** [rogeriocamorim/duneBugSuggestionTracker#7]
It would be nice if the game somehow informed the players, when they are trying to make an illegal play instead of simply not doing anything. I've seen people get stuck because they did not realize they were lacking influence needed to go to a spot or the resources.

**Comment by Chatanga** [comment]
Definitely on the road map, but not on the top priority list.

**Comment by Chatanga** [comment]
Fixed in [Fixed issues:](https://github.com/aaittouares/Dune_Uprising_TTS/commit/e68cdf5f44e2b1950e3d8d695fadf463d477e490)
