### ISSUE TITLE
Contracts don't autofill until after leaders are selected

### ISSUE THREAD

**Issue by 4thQueen** [rogeriocamorim/duneBugSuggestionTracker#8]
The two starting contracts should be filled at the same time the Imperium Row is set up, it is public knowledge before leaders are selected.

**Comment by Chatanga** [comment]
I unconsciously took the liberty of rearranging the setup order slightly to avoid the situation where Shaddam would be chosen during leader selection when 1 or 2 of his contracts would have been selected first. I recognize that the rules say otherwise, but it might be good to amend them on this point. The same way the set up of the Throne Row would require further clarifications by the way.

**Comment by dotdotdot-tts** [comment]
would it be possible that if one of shaddam's contracts get revealed, you would just move it aside and draw another to replace it after shaddam gets picked?

regarding shaddam contracts, they should be on the board and not in shaddam's player area. this has led to newer players incorrectly assuming they DO NOT need to acquire them via contract spaces.

would be nice if it's just on the board like this:
![shaddam contracts](https://github.com/rogeriocamorim/duneBugSuggestionTracker/assets/154347378/a0856cff-8150-4454-83e9-8d52428e5ffc)

**Comment by dotdotdot-tts** [comment]
this is live now, thank you!

any consideration to putting the shaddam contracts on the board instead of the player's area?

**Comment by aaittouares** [comment]
> this is live now, thank you!
> 
> any consideration to putting the shaddam contracts on the board instead of the player's area?

no consideration about this, sorry.
people should read and know the rules, and "set aside" is pretty clear.
I could also argue that with your contracts display proposal, some newcomers that didn't read the rules of shaddam could come and acquire shaddam contracts believing they are available to everyone.

Sardaukar contracts are set aside on the leader and not in the contracts columns (wich is what happen  like when you click over a contract to acquire it). That makes it pretty clear they are not acquired. 

Issue closed
